theme: jekyll-theme-minimal
title: The Bookware Group
logo: /assets/img/bookware.png
description: Bookware is a group that discusses books and other sources of knowledge related to software.
google_analytics: G-SFKP6BEHDD